### PR TITLE
Add `templates_base_dir` option to change templates directory

### PR DESCRIPTION
**Pull request by syou6162**
## WHAT
I added `templates_base_dir` option to change the templates directory (Current default `templates_base_dir` seems `dbt_helper/templates`).

## WHY
In `model.sql.tmpl`, current templates goes as follow:

```
  config(
    enabled=true,
    ...
    labels={
      "modeled": "dbt",
      "contains_pii": "false | true",
      "owner": model_owner,
      {% for k, v in labels.items() -%}
      "{{- k -}}": "{{- v -}}",
```

I want to control the labels inserted as default such as `modeled`, `contains_pii`. I think it's great if I can specify my custom template directory. So I wrote this pull request.

```
% cp -r dbt_helper/templates /tmp

# modifying template...
% vim /tmp/templates/v2/model/model.sql.tmpl 

# specify the my custom templates directory
% dbt-helper model scaffold --models_dir models --project_alias my-project \
      --dataset my-dataset --table my-table --owner "syou6162" --materialization table \
      --overwrite --templates_base_dir /tmp/templates/

# Note: default behavior does not change
% dbt-helper model scaffold --models_dir models --project_alias my-project \
      --dataset my-dataset --table my-table --owner "syou6162" --materialization table \
      --overwrite
```

## ISSUES
NA

## Logs in your local machine
Please write parts of logs of `dbt run` locally here.

```
% dbt run --profiles-dir . --full-refresh --target local
Running with dbt=0.20.0
Found 5 models, 13 tests, 0 snapshots, 0 analyses, 164 macros, 0 operations, 0 seed files, 5 sources, 2 exposures

23:56:31 | Concurrency: 4 threads (target='local')
23:56:31 |
23:56:31 | 1 of 5 START table model test_test.examples_with_tweet_stats_v_0_0_2. [RUN]
```

## SANITY CHECKS :warning:
Please make sure you are aware of the following before opening the PR:

- [ ] Did you fill in the owner information?
  - I could not understand the owner information. What kind of information should I write? Is there any reference?
- [x] Is `dbt-helper` the latest version?

### CODE REVIEW

**Comment by yu-iskw** [comment]
@syou6162 Thank you for the contribution. Can you add a test case with `--templates_base_dir`. 

Moreover, it would be nicer to add the option to the other sub commands to generate files as `dbt source importing`.

**Comment by yu-iskw** [comment]
@syou6162 Aside from that, please feel free to assign a PR to me so that I receive a notification from GitHub.

**Comment by syou6162** [comment]
@yu-iskw Thank you for reviewing!

> Can you add a test case with --templates_base_dir.

OK, I'll add some test cases in `tests/cli/test_utils.py` later!

> Moreover, it would be nicer to add the option to the other sub commands to generate files as dbt source importing.

I'll also add `--templates_base_dir` option to other sub command.

> please feel free to assign a PR to me so that I receive a notification from GitHub.

Sorry, I cannot assign this PR to you because I don't have the assignment permission in this repository (maybe. I don't have the way to confirm it...).

スクリーンショット 2021-08-12 13 39 01

**Comment by yu-iskw** [comment]
> Sorry, I cannot assign this PR to you because I don't have the assignment permission in this repository (maybe. I don't have the way to confirm it...).

I got it. Alright, I have change `CODEOWNERS`. If you send a PR next time, I will be assigned by default.
https://github.com/yu-iskw/dbt-bigquery-project-template/pull/10

**Comment by syou6162** [comment]
@yu-iskw I added `--templates_base_dir` option for these sub commands:

- dbt-helper analysis scaffold
- dbt-helper model scaffold
- dbt-helper snapshot scaffold
- dbt-helper source importing
- dbt-helper source scaffold

And I also added test cases for this options. Please review my pull request...!

**Comment by syou6162** [comment]
@yu-iskw Could you please review my pull request?

**Comment by syou6162** [comment]
@yu-iskw Several month has passed since I send you this pull request.

We are using dbt & dbt-helper to build complex DWH on production. Although we can use dbt-helper on forked version, but it would not be happy for dbt community.

If there are some points to fix, I'll try to fix it!! So please give any commets.

**Pull request closed without merging**
